# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travel_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travel_start',
            field=models.DateField(),
        ),
    ]
